--- #YAML:1.0
name:                Geo-ISO19139
version:             0.10
abstract:            Geography metadata standard
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Geo::GML:                      0.12
    Log::Report:                   0.19
    Test::More:                    0.54
    Test::Pod:                     1.00
    XML::Compile:                  0.84
    XML::Compile::Cache:           0.10
    XML::Compile::Tester:          0.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
